server:
  port: 8082
spring:
  security:
    user:
      password: dev_$tudentcase
      username: dev%studentcase
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:h2:mem:devdb
    driverClassName: org.h2.Driver
    username: dev
    password: dev
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
##JWT
jwt:
  secret: dev_studentcase
