server:
  port: 8082
spring:
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    url: jdbc:h2:mem:stagedb
    driverClassName: org.h2.Driver
    username: stage
    password: stage
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
##JWT
